# Docker Compose 简化版配置文件
# 仅包含: HTML2MD核心服务

services:
  # HTML转Markdown服务
  html2md:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html2md-service
    restart: unless-stopped
    environment:
      # 服务配置
      - HTTP_PORT=8080
      - GRPC_PORT=9090
      - ENVIRONMENT=production
      - SERVICE_NAME=html2md
      - SERVICE_VERSION=1.0.0
      
      # 日志配置
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - LOG_OUTPUT=stdout
      
      # 转换器配置
      - CONVERTER_MAX_INPUT_SIZE=10485760  # 10MB
      - CONVERTER_MAX_BATCH_SIZE=100
      - CONVERTER_DEFAULT_PLUGINS=base,commonmark
      - CONVERTER_TIMEOUT=30s
    ports:
      - "8080:8080"  # HTTP API
      - "9090:9090"  # GRPC API
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25' 