basePath: /
definitions:
  model.APIResponse:
    properties:
      code:
        description: 业务响应码
        example: 200
        type: integer
      data:
        description: 返回数据
      msg:
        description: 接口消息
        example: success
        type: string
    type: object
  model.BatchConvertItem:
    properties:
      error:
        description: 错误信息（失败时）
        example: 转换失败
        type: string
      index:
        description: 项目索引
        example: 0
        type: integer
      result:
        allOf:
        - $ref: '#/definitions/model.ConvertResponse'
        description: 转换结果（成功时）
      success:
        description: 是否成功
        example: true
        type: boolean
    type: object
  model.BatchConvertRequest:
    properties:
      items:
        description: 批量转换项目，最多100个
        items:
          $ref: '#/definitions/model.ConvertRequest'
        maxItems: 100
        minItems: 1
        type: array
    required:
    - items
    type: object
  model.BatchConvertResponse:
    properties:
      results:
        description: 批量转换结果
        items:
          $ref: '#/definitions/model.BatchConvertItem'
        type: array
      summary:
        allOf:
        - $ref: '#/definitions/model.BatchSummary'
        description: 批量转换摘要
    type: object
  model.BatchSummary:
    properties:
      average_time:
        description: 平均处理时间
        example: 500ms
        type: string
      failed:
        description: 失败数
        example: 2
        type: integer
      success:
        description: 成功数
        example: 8
        type: integer
      total:
        description: 总数
        example: 10
        type: integer
      total_time:
        description: 总处理时间
        example: 5s
        type: string
    type: object
  model.ConversionStats:
    properties:
      input_size:
        description: 输入HTML大小（字节）
        example: 1024
        type: integer
      output_size:
        description: 输出Markdown大小（字节）
        example: 512
        type: integer
      plugins_used:
        description: 使用的插件列表
        example:
        - base
        - commonmark
        items:
          type: string
        type: array
      processing_time:
        description: 处理时间
        example: 100ms
        type: string
    type: object
  model.ConvertRequest:
    properties:
      domain:
        description: 基础域名，用于转换相对链接
        example: https://example.com
        type: string
      html:
        description: HTML内容
        example: <h1>Hello World</h1>
        type: string
      plugins:
        description: 启用的插件
        example:
        - base
        - commonmark
        items:
          type: string
        type: array
    required:
    - html
    type: object
  model.ConvertResponse:
    properties:
      markdown:
        description: 转换后的Markdown内容
        example: '# Hello World'
        type: string
      stats:
        allOf:
        - $ref: '#/definitions/model.ConversionStats'
        description: 转换统计信息
    type: object
  model.HealthResponse:
    properties:
      memory:
        allOf:
        - $ref: '#/definitions/model.MemInfo'
        description: 内存信息
      status:
        description: 服务状态
        example: ok
        type: string
      timestamp:
        description: 检查时间
        example: "2023-12-01T12:00:00Z"
        type: string
      uptime:
        description: 运行时间
        example: 1h30m
        type: string
      version:
        description: 服务版本
        example: 1.0.0
        type: string
    type: object
  model.MemInfo:
    properties:
      alloc:
        description: 已分配内存（字节）
        example: 1048576
        type: integer
      num_gc:
        description: GC次数
        example: 5
        type: integer
      sys:
        description: 系统内存（字节）
        example: 4194304
        type: integer
      total_alloc:
        description: 总分配内存（字节）
        example: 2097152
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://github.com/relaxcloud-cn/html2md/issues
  description: HTML转Markdown转换服务的REST API
  license:
    name: MIT
    url: https://github.com/relaxcloud-cn/html2md/blob/main/LICENSE
  termsOfService: https://github.com/relaxcloud-cn/html2md
  title: HTML2Markdown API
  version: "1.0"
paths:
  /api/v1/convert:
    post:
      consumes:
      - application/json
      description: 将HTML内容转换为Markdown格式，支持多种转换选项和插件
      parameters:
      - description: 转换请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ConvertRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 转换成功
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ConvertResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data: {}
              type: object
        "500":
          description: 内部服务器错误
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data: {}
              type: object
      summary: 转换HTML为Markdown
      tags:
      - 转换
  /api/v1/convert/batch:
    post:
      consumes:
      - application/json
      description: 批量转换多个HTML内容为Markdown格式
      parameters:
      - description: 批量转换请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.BatchConvertRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 转换成功
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.BatchConvertResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data: {}
              type: object
        "500":
          description: 内部服务器错误
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data: {}
              type: object
      summary: 批量转换HTML为Markdown
      tags:
      - 转换
  /api/v1/convert/simple:
    get:
      consumes:
      - text/plain
      description: 通过URL参数进行简单的HTML转换，适用于快速测试
      parameters:
      - description: HTML内容
        in: query
        name: html
        required: true
        type: string
      - description: 插件列表，逗号分隔
        example: '"base,commonmark"'
        in: query
        name: plugins
        type: string
      - description: 基础域名
        example: '"https://example.com"'
        in: query
        name: domain
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 转换成功
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ConvertResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data: {}
              type: object
        "500":
          description: 内部服务器错误
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data: {}
              type: object
      summary: 简单HTML转换（GET方式）
      tags:
      - 转换
  /api/v1/demo:
    get:
      description: 提供一个简单的演示页面，展示API的使用方法
      produces:
      - text/html
      responses:
        "200":
          description: HTML演示页面
          schema:
            type: string
      summary: 演示接口
      tags:
      - 演示
  /api/v1/health:
    get:
      description: 检查服务健康状态和运行信息
      produces:
      - application/json
      responses:
        "200":
          description: 服务正常
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.HealthResponse'
              type: object
        "500":
          description: 服务异常
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data: {}
              type: object
      summary: 健康检查
      tags:
      - 系统
  /api/v1/info:
    get:
      description: 获取转换器版本、支持的插件和功能信息
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  additionalProperties: true
                  type: object
              type: object
      summary: 获取转换器信息
      tags:
      - 系统
schemes:
- http
- https
swagger: "2.0"
